---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# BLSA MIMS project

<!-- badges: start -->
<!-- badges: end -->

<<<<<<< HEAD
The project uses raw accelerometry data from ~700 participants in Baltimore Longitudinal Study of Aging (BLSA), each monitored for approx. 1 week with a wrist-worn ActiGraph sensor.  


1. We wish to determine if alternative measures of physical activity, derived from the raw acceleration signals, track similarly with health outcomes as activity counts.  Namely, we focus on open-source pipelines and implementations to transform raw files into activity summaries.  
2. As activity counts have been used in a number of studies and activity-level thresholds have been derived, we wish to estimate equivalent thresholds in these open-source measures to allow for similar analysis done with activity counts. 
3. We describe the advantages of using these open source tools and present an R package that can aid in this analysis, while also providing the source code to generate our analysis. 

The goal of the project is to:

1. Develop and use R software to aggregate raw data at minute-level with open-source measures: MIMS, ENMO, MAD, AI.

2. Quantify association between AC and open-source measures marginally and conditionally on age, sex and BMI. 

3. Harmonize minute-level AC with open-source measures via one-to-one mapping.  

4. Reproduce some of the published BLSA results that used AC with the use of the open-source measures. 



# Repository navigation

For practitioners, potentially most useful R code scripts and result files are referenced below. 

### Methods 

- R code script to generate raw data quality check flags: [code/data_preprocessing/mat_to_minute_quality_flag.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/mat_to_minute_quality_flag.R)

- R code script to compute MIMS, MAD, AI: [code/data_preprocessing/mat_to_open_source_measures.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/mat_to_open_source_measures.R)

- R code script to compute ENMO (with data calibration step):  [code/data_preprocessing/mat_calibrated_to_open_source_measures.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/mat_calibrated_to_open_source_measures.R)

- R code script to compute valid minute and valid day flags and to filter the participants: [code/data_preprocessing/prepare_measures_masterfile.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/prepare_measures_masterfile.R)

- R code script to perform data imputation: [code/data_preprocessing/prepare_measures_masterfile_winsorized_imp.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/prepare_measures_masterfile_winsorized_imp.R)

### Results 

- CSV table with model-fitted values of MIMS, ENMO, MAD, AI for a range of AC values: [results_public/mapping_between_measures_FITTED.txt](https://raw.githubusercontent.com/muschellij2/blsa_mims/master/results_public/mapping_between_measures_FITTED.txt)

- R code script with fast mapping functions between AC and MIMS, ENMO, MAD, AI: [code/data_preprocessing/measures_mapping_FUNC.R](https://github.com/muschellij2/blsa_mims/blob/master/code/data_preprocessing/measures_mapping_FUNC.R)




# Citation
The paper is located at https://doi.org/10.2196/38077.

Please cite this work as:
```
@article{karas2022comparison,
  title={Comparison of accelerometry-based measures of physical activity: Retrospective observational data analysis study},
  author={Karas, Marta and Muschelli, John and Leroux, Andrew and Urbanek, Jacek K and Wanigatunga, Amal A and Bai, Jiawei and Crainiceanu, Ciprian M and Schrack, Jennifer A},
  journal={JMIR mHealth and uHealth},
  volume={10},
  number={7},
  pages={e38077},
  year={2022},
  publisher={JMIR Publications Toronto, Canada}
}
```


# Previous Repo documentation 

## code

* `add_nonwear.R` -- runs WearNonWear function; reads files with suffix `60sec.csv.gz` from `/csv`, runs WearNonWear algorithm, saves as file with suffix `_nonwear.csv.gz`[MK: TODO JM was it actually saved? I do not see any such files in `/csv`]
* `ag_read.R` -- contains code to read gt3x files with `AGread::read_gt3x` 
* `check_dims.R` -- runs `read_xi_dims` function from  `/code/helper_functions` to check for correctness of the dimensions of files from `mats` dir
* `check_gt3x_vs_csv.R` -- runs checks related to open-source reading of acc data files
* `check_gt3x_vs_mat.R` -- runs checks related to open-source reading of acc data files
* `compare_nonwear.R` -- TODO JM
* `get_metadata.R` -- runs extraction of meta data (Acceleration Max, Acceleration Min, Serial Number, Device Type) for all files in `/gt3x` and saves summary at `results/device_info.rds`
* `gt3x_read.R` -- contains code to read gt3x files with `AGread::read_gt3x` [TODO JM : how it differs from `ag_read.R` ? ]
* `helper_functions.R` -- contains set of util functions, including: 
    * `round_away_zero` -- TODO JM 
    * `quick_ai` -- TODO JM 
    * `full_measures` -- gets all measures to compare other than MIMS
    * `mad` -- short function for MAD
    * `get_dynamic_range` -- get the dynamic range in g from header (from Jacek header)
    * `read_mat` -- general function to read in matlab .mat
    * `read_acc_mat` -- specific function to read in Jacek accelerometry .mat
    * `sub_thing` -- util for parsing the header from RAW csv from Actilife
    * `WearNonWear` -- from Jacek - implementation of Choi
    * `tabber` -- quick tabulation function of long logicals
    * `cwa_mims` -- get MIMS from a CWA file (for Biobank)
    * `read_xi_dims` -- TODO JM 
* `make_mims.R` -- runs `SummarizedActigraphy::read_acc_csv` function to derive MIMS for all files at `/gt3x`; saves result at `/open_measures/` as `_MIMS.csv.gz` suffix files [TODO JM : am I right it used /gt3x?]
* `make_thresholds.R` -- runs code to estimate mapping between values of metrics with gam models; note comments for any data pre-filtering done
* `mat_make_mims.R` -- TODO JM
* `plot_comparison.R` -- generates data plots
* `resample_data.R` -- TODO JM
* `rsync_gt3x.R` -- script to upload `/gt3x` files from external location 
* `WearNonWear.R` -- wear/non-wear algorithm; likely former version of [arctools/R/get_wear_flag.R](https://github.com/martakarass/arctools/blob/master/R/get_wear_flag.R) 
