---
title: "EDA - measures summaries"
author: "Marta Karas"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
  pdf_document:
    toc: yes
    toc_depth: '5'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)
library(data.table)
library(tidyverse)
library(ggsci) # color https://cran.r-project.org/web/packages/ggsci/vignettes/ggsci.html
gg_base_size <- 12
options(scipen=999)
```

### Download data 

```
sftp mkaras@jhpce-transfer01.jhsph.edu

get /dcl01/smart/data/activity/blsa_mims/results/2021-01-11-device_and_data_range_info.rds /Users/martakaras/Dropbox/_PROJECTS/blsa_mims/results/2021-01-11-device_and_data_range_info.rds

get /dcl01/smart/data/activity/blsa_mims/results/2021-01-15-measures_vals_summary_per_participant.rds /Users/martakaras/Dropbox/_PROJECTS/blsa_mims/results/2021-01-15-measures_vals_summary_per_participant.rds

get /dcl01/smart/data/activity/blsa_mims/results/2021-01-15-measures_vals_summary_population.rds /Users/martakaras/Dropbox/_PROJECTS/blsa_mims/results/2021-01-15-measures_vals_summary_population.rds

get /dcl01/smart/data/activity/blsa_mims/results/2021-01-15-osm_ac_corr.rds /Users/martakaras/Dropbox/_PROJECTS/blsa_mims/results/2021-01-15-osm_ac_corr.rds
```

### Read data 

```{r}
fpath_tmp <- paste0(here::here(), "/results/2021-01-11-device_and_data_range_info.rds")
dat_device_meta <- readRDS(fpath_tmp)
head(dat_device_meta)

fpath_tmp <- paste0(here::here(), "/results/2021-01-15-measures_vals_summary_per_participant.rds")
dat_sum_perpar <- readRDS(fpath_tmp)
head(dat_sum_perpar)

fpath_tmp <- paste0(here::here(), "/results/2021-01-15-measures_vals_summary_population.rds")
dat_sum_popul <- readRDS(fpath_tmp)
head(dat_sum_popul)

fpath_tmp <- paste0(here::here(), "/results/2021-01-15-osm_ac_corr.rds")
dat_corr <- readRDS(fpath_tmp)
head(dat_corr)
```

### Device meta data

```{r}
nrow(dat_device_meta)

table(dat_device_meta$dynamic_range_min)
table(dat_device_meta$dynamic_range_max)

summary(dat_device_meta$accel_min)
summary(dat_device_meta$accel_max)
```


### 1st visit: number of valid days per participant 

```{r}
plt_df <- dat_sum_perpar %>%
  select(subj_id, visit_id, validdays_cnt) %>%
  distinct()

table(plt_df$validdays_cnt)
```


### Minute-level measures: summary of values across population

```{r}
dat_sum_popul
```


### Minute-level measures: summary of corr across population

```{r}
col_corr <- c(
  "AC_MIMS",
  "AC_MAD",
  "AC_ENMO",
  "AC_AI",
  "MIMS_MAD",
  "MIMS_ENMO",
  "MIMS_AI",
  "MAD_ENMO",
  "MAD_AI",
  "ENMO_AI"
)

dat_corr_agg <- 
  dat_corr %>%
  select(all_of(c("wearflag_only", "from11to5_excl", "vals_windsorized", col_corr)))

dat_corr_agg_mean <- 
  dat_corr_agg %>% 
  group_by(wearflag_only, from11to5_excl, vals_windsorized) %>%
  summarise_all(mean, na.rm = TRUE) %>%
  as.data.frame()

dat_corr_agg_mean

dat_corr_agg_mean_NW <- 
  dat_corr_agg_mean %>% 
  filter(vals_windsorized == 0) %>%
  select(-vals_windsorized) %>%
  arrange(from11to5_excl, wearflag_only)

dat_corr_agg_mean_WW <- 
  dat_corr_agg_mean %>% 
  filter(vals_windsorized == 1) %>%
  select(-vals_windsorized) %>%
  arrange(from11to5_excl, wearflag_only)


dat_corr_agg_mean_NW
dat_corr_agg_mean_WW

```








